Voici les CIP des membres de l'équipe

- Karl Plourde - PLOK2502

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.max_rows', 20)
pd.set_option('display.max_columns', 20)

In [2]:
df_data = pd.read_csv('data\data.csv')
df_labels = pd.read_csv('data\labels.csv')

#Merge data and labels
df_merge = pd.merge(df_data, df_labels, left_index=True, right_index=True)
df_merge.rename(columns={"Unnamed: 0_x":'ID'}, inplace=True)
df_merge.drop(['Unnamed: 0_y'], axis=1, inplace=True)
df_merge.head()

,ID,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530,Class
0,sample_0,0.0,2.017209,3.265527,5.478487,10.431999,0.0,7.175175,0.591871,0.0,...,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759,0.0,PRAD
1,sample_1,0.0,0.592732,1.588421,7.586157,9.623011,0.0,6.816049,0.000000,0.0,...,7.323865,9.740931,6.256586,8.381612,12.674552,10.517059,9.397854,2.094168,0.0,LUAD
2,sample_2,0.0,3.511759,4.327199,6.881787,9.870730,0.0,6.972130,0.452595,0.0,...,8.127123,10.908640,5.401607,9.911597,9.045255,9.788359,10.090470,1.683023,0.0,PRAD
3,sample_3,0.0,3.663618,4.507649,6.659068,10.196184,0.0,7.843375,0.434882,0.0,...,8.792959,10.141520,8.942805,9.601208,11.392682,9.694814,9.684365,3.292001,0.0,PRAD
4,sample_4,0.0,2.655741,2.821547,6.539454,9.738265,0.0,6.566967,0.360982,0.0,...,8.891425,10.373790,7.181162,9.846910,11.922439,9.217749,9.461191,5.110372,0.0,BRCA

In [3]:
#Calculate the threshold for the percentage of zeros
threshold = 0.3 

# Calculate the maximum allowed number of zeros
max_zeros = len(df_merge) * threshold

# Filter columns with 80% or more zeros
filtered_columns = df_merge.columns[(df_merge == 0).sum() <= max_zeros]

# Create a new DataFrame with selected columns
filtered_data = df_merge[filtered_columns]

# Display the modified DataFrame
filtered_data.head()

,ID,gene_1,gene_2,gene_3,gene_4,gene_6,gene_11,gene_12,gene_19,gene_20,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,Class
0,sample_0,2.017209,3.265527,5.478487,10.431999,7.175175,1.334282,2.015391,5.619994,1.334282,...,4.926711,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759,PRAD
1,sample_1,0.592732,1.588421,7.586157,9.623011,6.816049,0.587845,2.466601,11.055208,3.562621,...,4.593372,7.323865,9.740931,6.256586,8.381612,12.674552,10.517059,9.397854,2.094168,LUAD
2,sample_2,3.511759,4.327199,6.881787,9.870730,6.972130,0.452595,1.981122,8.210248,4.195285,...,5.125213,8.127123,10.908640,5.401607,9.911597,9.045255,9.788359,10.090470,1.683023,PRAD
3,sample_3,3.663618,4.507649,6.659068,10.196184,7.843375,0.434882,2.874246,8.306317,3.573556,...,6.076566,8.792959,10.141520,8.942805,9.601208,11.392682,9.694814,9.684365,3.292001,PRAD
4,sample_4,2.655741,2.821547,6.539454,9.738265,6.566967,1.275841,2.141204,10.149150,2.967630,...,5.996032,8.891425,10.373790,7.181162,9.846910,11.922439,9.217749,9.461191,5.110372,BRCA

In [4]:
#Make a dataframe for each value of PRAD LUAD BRCA KIRC COAD
df_prad = filtered_data[filtered_data['Class'] == 'PRAD']
df_luad = filtered_data[filtered_data['Class'] == 'LUAD']
df_brca= filtered_data[filtered_data['Class'] == 'BRCA']
df_kirc = filtered_data[filtered_data['Class'] == 'KIRC']
df_coad = filtered_data[filtered_data['Class'] == 'COAD']

#Remove Class column and ID column
df_coad= df_coad.iloc[:,1:-1]

df_kirc= df_kirc.iloc[:,1:-1]

df_brca= df_brca.iloc[:,1:-1]

df_luad= df_luad.iloc[:,1:-1]

df_prad = df_prad.iloc[:,1:-1]

In [5]:
# Calculate the correlation matrix
correlation_matrix_prad = df_prad.corr().abs()

# Set the threshold for correlation
threshold = 0.80

# Find columns with correlation greater than or equal to the threshold
high_corr_columns = np.where(correlation_matrix_prad >= threshold)

# Create a set to store columns to remove
columns_to_remove = set()

# Iterate through the pairs of highly correlated columns
for col1, col2 in zip(*high_corr_columns):
    if col1 != col2 and col1 not in columns_to_remove:
        columns_to_remove.add(col2)

# Remove the identified columns
df_prad_filtered = df_prad.drop(columns=df_prad.columns[list(columns_to_remove)],axis=1)
df_prad_filtered.head()

,gene_1,gene_2,gene_3,gene_4,gene_6,gene_11,gene_12,gene_19,gene_20,gene_22,...,gene_20515,gene_20516,gene_20518,gene_20519,gene_20520,gene_20521,gene_20524,gene_20527,gene_20528,gene_20529
0,2.017209,3.265527,5.478487,10.431999,7.175175,1.334282,2.015391,5.619994,1.334282,9.796088,...,7.175175,9.249369,8.045563,7.475709,7.205236,4.926711,7.220030,9.650743,8.921326,5.286759
2,3.511759,4.327199,6.881787,9.870730,6.972130,0.452595,1.981122,8.210248,4.195285,8.970920,...,7.716332,6.745802,8.602350,9.036654,10.336027,5.125213,5.401607,9.788359,10.090470,1.683023
3,3.663618,4.507649,6.659068,10.196184,7.843375,0.434882,2.874246,8.306317,3.573556,8.524616,...,8.963286,7.744699,8.981473,8.665592,9.194823,6.076566,8.942805,9.694814,9.684365,3.292001
5,3.467853,3.581918,6.620243,9.706829,7.758510,0.515410,2.516797,6.842765,2.809661,7.663935,...,8.380816,7.792270,8.664963,8.344820,7.831035,5.726657,6.096154,9.244150,9.836473,5.355133
7,2.854853,1.750478,7.226720,9.758691,5.952103,0.000000,2.405856,7.373431,2.304861,8.922008,...,8.468738,8.466199,8.358093,7.422199,6.460507,5.297833,5.244290,9.987733,9.216872,6.551490

In [6]:
# Calculate the correlation matrix
correlation_matrix_luad = df_luad.corr().abs()

# Set the threshold for correlation
threshold = 0.80

# Find columns with correlation greater than or equal to the threshold
high_corr_columns = np.where(correlation_matrix_luad >= threshold)

# Create a set to store columns to remove
columns_to_remove = set()

# Iterate through the pairs of highly correlated columns
for col1, col2 in zip(*high_corr_columns):
    if col1 != col2 and col1 not in columns_to_remove:
        columns_to_remove.add(col2)

# Remove the identified columns
df_luad_filtered = df_luad.drop(columns=df_luad.columns[list(columns_to_remove)],axis=1)
df_luad_filtered.head()

,gene_1,gene_2,gene_3,gene_4,gene_6,gene_11,gene_12,gene_19,gene_20,gene_22,...,gene_20518,gene_20519,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20529
1,0.592732,1.588421,7.586157,9.623011,6.816049,0.587845,2.466601,11.055208,3.562621,10.070470,...,9.458940,9.190867,4.593372,7.323865,9.740931,6.256586,8.381612,12.674552,10.517059,2.094168
16,3.460913,3.618474,5.661048,9.731217,8.435591,2.640644,2.719205,10.103576,5.679936,9.097097,...,7.498019,7.795481,5.350285,8.197320,9.907260,0.763921,10.088854,11.471137,9.768648,2.932118
22,1.131853,2.351515,6.845841,9.196860,7.853827,4.201469,2.564817,9.986724,5.412903,6.329574,...,9.222662,8.368066,5.235987,8.400832,9.524792,7.891079,10.579429,12.098697,10.550256,5.250397
25,4.317702,3.642678,6.790003,8.435999,8.573628,1.757706,2.313043,9.708972,5.045229,8.758640,...,8.528849,7.771417,6.290371,8.951419,10.445253,1.757706,9.709429,12.364996,11.175213,4.912085
37,4.416259,4.188978,6.664198,9.070819,7.915318,1.857026,2.168899,9.107863,4.568598,7.941206,...,8.777995,7.754193,5.786609,8.302470,10.431884,2.168899,9.402496,12.072283,10.637458,6.148450

In [7]:
# Calculate the correlation matrix
correlation_matrix_brca = df_brca.corr().abs()

# Set the threshold for correlation
threshold = 0.80

# Find columns with correlation greater than or equal to the threshold
high_corr_columns = np.where(correlation_matrix_brca >= threshold)

# Create a set to store columns to remove
columns_to_remove = set()

# Iterate through the pairs of highly correlated columns
for col1, col2 in zip(*high_corr_columns):
    if col1 != col2 and col1 not in columns_to_remove:
        columns_to_remove.add(col2)

# Remove the identified columns
df_brca_filtered = df_brca.drop(columns=df_brca.columns[list(columns_to_remove)],axis=1)
df_brca_filtered.head()

,gene_1,gene_2,gene_3,gene_4,gene_6,gene_11,gene_12,gene_19,gene_20,gene_22,...,gene_20520,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529
4,2.655741,2.821547,6.539454,9.738265,6.566967,1.275841,2.141204,10.149150,2.967630,8.047238,...,9.298775,5.996032,8.891425,10.373790,7.181162,9.846910,11.922439,9.217749,9.461191,5.110372
8,3.992125,2.772730,6.546692,10.488252,7.690222,1.252839,2.579977,10.147625,4.287908,8.343976,...,10.461326,6.721974,9.597533,9.763753,7.933278,10.952880,12.498919,10.389954,10.390255,7.828321
10,3.492071,3.553373,7.151707,10.253446,8.301258,1.999567,3.381962,7.965224,2.146395,8.115408,...,9.404882,6.231006,9.061674,10.042261,6.580103,9.785004,12.383834,9.869359,8.991768,5.735121
13,1.551048,3.529846,6.326825,10.633849,8.944659,0.501821,2.479282,8.526534,0.000000,10.717848,...,11.119337,3.920732,7.846901,9.379835,7.195800,8.907645,12.079481,9.218936,8.104101,3.660894
14,1.964842,2.183010,6.596832,10.248141,7.087251,0.000000,2.896214,7.993499,2.750306,9.580091,...,10.266295,6.078847,10.829588,10.404567,6.588536,8.952596,10.461725,10.582857,9.488141,3.261967

In [8]:
# Calculate the correlation matrix
correlation_matrix_kirc = df_kirc.corr().abs()

# Set the threshold for correlation
threshold = 0.80

# Find columns with correlation greater than or equal to the threshold
high_corr_columns = np.where(correlation_matrix_kirc >= threshold)

# Create a set to store columns to remove
columns_to_remove = set()

# Iterate through the pairs of highly correlated columns
for col1, col2 in zip(*high_corr_columns):
    if col1 != col2 and col1 not in columns_to_remove:
        columns_to_remove.add(col2)

# Remove the identified columns
df_kirc_filtered = df_kirc.drop(columns=df_kirc.columns[list(columns_to_remove)],axis=1)
df_kirc_filtered.head()

,gene_1,gene_2,gene_3,gene_4,gene_6,gene_11,gene_12,gene_19,gene_20,gene_22,...,gene_20517,gene_20518,gene_20519,gene_20522,gene_20523,gene_20524,gene_20526,gene_20527,gene_20528,gene_20529
6,1.224966,1.691177,6.572007,9.640511,6.754888,1.476796,3.023841,7.424200,1.224966,9.973640,...,6.724787,7.507858,6.862712,7.927968,9.673966,1.877744,13.256060,9.664486,9.244219,8.330912
11,2.941181,2.663276,6.561690,9.376293,7.860323,1.021409,3.153092,9.796182,4.848317,8.614732,...,7.222080,8.198813,7.234137,8.395474,10.405099,5.070922,11.749802,10.397407,9.300561,5.276564
17,3.004519,3.007178,6.524205,9.062661,7.995937,1.077516,2.233060,8.317150,3.802669,7.697197,...,7.119553,8.346975,7.298860,8.702713,10.392532,2.711935,11.623369,10.327115,9.772328,3.597400
18,1.541465,2.541540,6.843255,9.444468,5.479091,0.401194,2.456438,10.602717,1.190615,8.026241,...,7.028227,8.188826,7.103917,8.619974,10.088165,2.178492,12.380688,10.741298,9.808642,5.777772
21,3.529783,2.976712,6.038416,9.437973,5.893828,0.000000,3.250537,10.199182,1.732443,8.697826,...,7.980968,9.228617,7.910757,9.186099,10.241781,1.349705,12.826908,9.538280,10.131587,7.738390

In [9]:
# Calculate the correlation matrix
correlation_matrix_coad = df_coad.corr().abs()

# Set the threshold for correlation
threshold = 0.80

# Find columns with correlation greater than or equal to the threshold
high_corr_columns = np.where(correlation_matrix_coad >= threshold)

# Create a set to store columns to remove
columns_to_remove = set()

# Iterate through the pairs of highly correlated columns
for col1, col2 in zip(*high_corr_columns):
    if col1 != col2 and col1 not in columns_to_remove:
        columns_to_remove.add(col2)

# Remove the identified columns
df_coad_filtered = df_coad.drop(columns=df_coad.columns[list(columns_to_remove)],axis=1)
df_coad_filtered.head()

,gene_1,gene_2,gene_3,gene_4,gene_6,gene_11,gene_12,gene_19,gene_20,gene_22,...,gene_20518,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529
26,2.325242,3.247092,8.174007,10.065053,7.487446,0.000000,2.759582,6.944554,2.951215,7.163660,...,8.745136,5.765299,9.582618,10.097084,0.566572,9.414850,12.513264,9.714840,9.413833,4.470146
47,3.446190,3.620962,7.171917,9.796559,8.175245,1.972509,2.218967,8.617963,3.823780,7.783575,...,8.647196,5.019635,8.453184,10.082854,0.000000,9.389552,12.123349,11.552194,9.052753,1.675093
54,2.554196,1.296134,8.770277,10.462901,8.013993,0.736562,3.543446,7.243802,3.221537,10.231857,...,7.985831,4.873543,8.185569,9.876580,1.736302,9.230261,12.363812,9.441293,9.639285,2.221630
57,3.667699,3.083179,7.997292,9.516886,7.925424,0.000000,3.762157,10.178167,2.797719,7.065637,...,9.017591,6.783260,9.257888,10.331936,0.732486,8.922457,12.182373,10.525648,9.444771,3.449205
65,3.821935,3.717605,7.593100,10.205964,7.613185,0.000000,1.982364,9.138154,2.787182,7.445346,...,8.900453,6.208320,9.137073,10.057464,0.000000,8.988114,12.993375,10.565978,9.184890,3.102541

In [10]:
# Make a list to check the dataframe that has the same columns for all the dataframes
df_list = [df_prad_filtered, df_luad_filtered, df_brca_filtered, df_kirc_filtered, df_coad_filtered]

# Create a set to store the common columns
common_columns = set(df_list[0].columns)

# Iterate through the DataFrames
for df in df_list:
    # Update the set with the common columns
    common_columns = common_columns.intersection(df.columns)

# Convert the set to a list
common_columns = list(common_columns)

# Create a new DataFrame with the common columns
df_prad_filtered_common = df_prad_filtered[common_columns]
df_luad_filtered_common = df_luad_filtered[common_columns]
df_brca_filtered_common = df_brca_filtered[common_columns]
df_kirc_filtered_common = df_kirc_filtered[common_columns]
df_coad_filtered_common = df_coad_filtered[common_columns]

In [11]:
df_luad_filtered_common.head()

,gene_10619,gene_778,gene_2669,gene_2531,gene_19641,gene_18952,gene_15615,gene_12866,gene_13277,gene_554,...,gene_6986,gene_9077,gene_11265,gene_4018,gene_9147,gene_7932,gene_5331,gene_2808,gene_15519,gene_6953
1,7.524424,11.963420,8.369593,10.181823,8.171132,10.732006,4.870552,7.508571,12.671663,10.881825,...,10.255808,4.095722,5.284673,7.061279,10.459462,14.782215,9.691757,10.116305,9.486519,8.768300
16,9.185376,11.551184,9.162711,9.698255,10.235583,10.356133,6.300905,7.560715,12.058059,9.810189,...,6.645818,7.431665,2.864592,9.455909,10.363040,11.196252,10.026012,9.143248,9.192280,6.211108
22,7.646155,10.941752,9.921820,9.162993,10.750715,10.198420,8.736260,6.070123,11.454803,9.151527,...,7.221684,9.582974,4.315472,11.151784,10.915155,12.499701,9.151527,10.485890,8.994571,5.256690
25,8.587586,11.256421,9.335122,9.793568,11.208344,9.144566,7.003062,7.934959,9.957276,9.026546,...,6.023213,6.762349,5.045229,9.451473,10.525658,10.451520,9.622985,9.429495,9.118017,6.727144
37,10.231401,11.366918,9.288128,9.719144,10.323854,8.996219,6.331856,7.064786,10.024170,8.092107,...,7.111136,6.628055,3.726700,9.900307,10.480356,10.556746,9.696522,9.853359,9.807650,5.927550

In [12]:
df_prad_filtered_common.shape

(136, 11802)

In [13]:
# sample
np.random.seed(1)

df_prad_filtered_common = df_prad_filtered_common.sample(axis=1, n=4000)
df_luad_filtered_common = df_luad_filtered_common[df_prad_filtered_common.columns]
df_brca_filtered_common = df_brca_filtered_common[df_prad_filtered_common.columns]
df_kirc_filtered_common = df_kirc_filtered_common[df_prad_filtered_common.columns]
df_coad_filtered_common = df_coad_filtered_common[df_prad_filtered_common.columns]

### Calculate intra distance for each cancer type BRCA, PRAD, LUAD, COAD, KIRC

In [14]:
#Calculate mahalanobis distance for intra class PRAD
#np.random.seed(1)

#df_sampled_prad = df_prad_filtered_common.sample(axis=1, n=6000)

df_prad_filtered_mean = df_prad_filtered_common.mean()

df_prad_filtered_cov = df_prad_filtered_common.cov()

df_prad_filtered_cov_inv = np.linalg.inv(df_prad_filtered_cov)

distances = []

for index in  range(0, df_prad_filtered_common.shape[0]):
    diff = df_prad_filtered_common.iloc[index, :].values - df_prad_filtered_mean.values
    distance = np.dot(diff.T, np.dot(df_prad_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))

max_intra_dist_prad = np.max(distances)

max_intra_dist_prad

np.float64(71.7096206533241)

In [15]:
#Calculate mahalanobis distance for intra class LUAD
np.random.seed(1)

#df_sampled_luad = df_luad_filtered_common.sample(axis=1, n=14000)

df_luad_filtered_mean = df_luad_filtered_common.mean()

df_luad_filtered_cov = df_luad_filtered_common.cov()

df_luad_filtered_cov_inv = np.linalg.inv(df_luad_filtered_cov)

distances = []

for index in  range(0, df_luad_filtered_common.shape[0]):
    diff = df_luad_filtered_common.iloc[index, :].values - df_luad_filtered_mean.values
    distance = np.dot(diff.T, np.dot(df_luad_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))

max_intra_dist_luad = np.max(distances)

max_intra_dist_luad

np.float64(122.80050227133447)

In [16]:
#Calculate mahalanobis distance for intra class BRCA
np.random.seed(1)

#df_sampled_brca = df_brca_filtered_common.sample(axis=1, n=14000)

df_brca_filtered_mean = df_brca_filtered_common.mean()

df_brca_filtered_cov = df_brca_filtered_common.cov()

df_brca_filtered_cov_inv = np.linalg.inv(df_brca_filtered_cov)

distances = []

for index in  range(0, df_brca_filtered_common.shape[0]):
    diff = df_brca_filtered_common.iloc[index, :].values - df_brca_filtered_mean.values
    distance = np.dot(diff.T, np.dot(df_brca_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))
    
max_intra_dist_brca = np.max(distances)

max_intra_dist_brca

np.float64(123.46222042897814)

In [17]:
#Calculate mahalanobis distance for intra class COAD
np.random.seed(1)

#df_sampled_coad = df_coad_filtered_common.sample(axis=1, n=14000)

df_coad_filtered_mean = df_coad_filtered_common.mean()

df_coad_filtered_cov = df_coad_filtered_common.cov()

df_coad_filtered_cov_inv = np.linalg.inv(df_coad_filtered_cov)

distances = []

for index in range(0, df_coad_filtered_common.shape[0]):
    diff = df_coad_filtered_common.iloc[index, :].values - df_coad_filtered_mean.values
    distance = np.dot(diff.T, np.dot(df_coad_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))
    
max_intra_dist_coad = np.max(distances)

max_intra_dist_coad

np.float64(93.34151310991162)

In [18]:
#Calculate mahalanobis distance for intra class KIRC
np.random.seed(1)

#df_sampled_kirc = df_kirc_filtered_common.sample(axis=1, n=14000)

df_kirc_filtered_mean = df_kirc_filtered_common.mean()

df_kirc_filtered_cov = df_kirc_filtered_common.cov()

df_kirc_filtered_cov_inv = np.linalg.inv(df_kirc_filtered_cov)

distances = []

for index in  range(0, df_kirc_filtered_common.shape[0]):
    diff = df_kirc_filtered_common.iloc[index, :].values - df_kirc_filtered_mean.values
    distance = np.dot(diff.T, np.dot(df_kirc_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))

max_intra_dist_kirc = np.max(distances)

max_intra_dist_kirc

np.float64(130.18616834642322)

### Calculate the overlap for each mahalanobis distance for each cancer type : PRAD-LUAD, PRAD-COAD, PRAD-KIRC, PRAD-BRCA

In [37]:
np.random.seed(1)

#df_sampled_luad = df_luad_filtered_common.sample(axis=1, n=14000)
#df_sampled_prad = df_prad_filtered_common.sample(axis=1, n=14000)


#df_luad_filtered_mean = df_luad_filtered_common.mean()
#df_prad_filtered_mean = df_prad_filtered_common.mean()

#df_luad_filtered_cov = df_luad_filtered_common.cov()
#df_prad_filtered_cov = df_prad_filtered_common.cov()

#df_luad_filtered_cov_inv = np.linalg.inv(df_luad_filtered_cov)
#df_prad_filtered_cov_inv = np.linalg.inv(df_prad_filtered_cov)

distances = []

#Take the center of df_prad_mean and luad_gene
for index in  range(0, df_luad_filtered_common.shape[0]):
    diff = df_luad_filtered_common.iloc[index, :].values - df_prad_filtered_mean.values
    distance = np.dot(diff, np.dot(df_luad_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))
    
minimum_inter_prad_luad = np.min(distances)


distances = []

#Take the center of df_luad_mean and prad_gene
for index in  range(0, df_prad_filtered_common.shape[0]):
    diff = df_prad_filtered_common.iloc[index, :].values - df_luad_filtered_mean.values
    distance = np.dot(diff, np.dot(df_prad_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))

minimum_inter_luad_prad = np.min(distances)

minimum_inter =  min(minimum_inter_prad_luad,minimum_inter_luad_prad)
print("La distance inter-classe entre luad et prad est de : ", minimum_inter)
overlap_prad_luad = (max_intra_dist_luad + max_intra_dist_prad)/(2*minimum_inter)
overlap_prad_luad

ValueError: operands could not be broadcast together with shapes (4001,) (4000,)

In [20]:
#PRAD-COAD
np.random.seed(1)

#df_sampled_coad = df_coad_filtered_common.sample(axis=1, n=14000)
#df_sampled_prad = df_prad_filtered_common.sample(axis=1, n=14000)


#df_coad_filtered_mean = df_coad_filtered_common.mean()
#df_prad_filtered_mean = df_prad_filtered_common.mean()

#df_coad_filtered_cov = df_coad_filtered_common.cov()
#df_prad_filtered_cov = df_prad_filtered_common.cov()

#df_coad_filtered_cov_inv = np.linalg.inv(df_coad_filtered_cov)
#df_prad_filtered_cov_inv = np.linalg.inv(df_prad_filtered_cov)

distances = []

#Take the center of df_prad_mean and coad_gene
for index in  range(0, df_coad_filtered_common.shape[0]):
    diff = df_coad_filtered_common.iloc[index, :].values - df_prad_filtered_mean.values
    distance = np.dot(diff, np.dot(df_coad_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))
    
minimum_inter_prad_coad = np.min(distances)


distances = []

#Take the center of df_coad_mean and prad_gene
for index in  range(0, df_prad_filtered_common.shape[0]):
    diff = df_prad_filtered_common.iloc[index, :].values - df_coad_filtered_mean.values
    distance = np.dot(diff, np.dot(df_prad_filtered_cov, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))

minimum_inter_coad_prad = np.min(distances)

minimum_inter =  min(minimum_inter_coad_prad,minimum_inter_prad_coad)
print("La distance inter-classe minimale entre les deux classes PRAD et COAD est de : ", minimum_inter)
overlap_prad_coad = (max_intra_dist_coad+max_intra_dist_prad)/(2*minimum_inter)
overlap_prad_coad

La distance inter-classe minimale entre les deux classes PRAD et COAD est de :  559.5133849113622

np.float64(0.14749525052862053)

In [21]:
#PRAD-KIRC
np.random.seed(1)

#df_sampled_kirc = df_kirc_filtered_common.sample(axis=1, n=14000)
#df_sampled_prad = df_prad_filtered_common.sample(axis=1, n=14000)


#df_kirc_filtered_mean = df_kirc_filtered_common.mean()
#df_prad_filtered_mean = df_prad_filtered_common.mean()

#df_kirc_filtered_cov = df_kirc_filtered_common.cov()
#df_prad_filtered_cov = df_prad_filtered_common.cov()

#df_kirc_filtered_cov_inv = np.linalg.inv(df_kirc_filtered_cov)
#df_prad_filtered_cov_inv = np.linalg.inv(df_prad_filtered_cov)

distances = []

#Take the center of df_prad_mean and kirc_gene
for index in  range(0, df_kirc_filtered_common.shape[0]):
    diff = df_kirc_filtered_common.iloc[index, :].values - df_prad_filtered_mean.values
    distance = np.dot(diff, np.dot(df_kirc_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))

minimum_inter_prad_kirc = np.min(distances)

distances = []

#Take the center of df_kirc_mean and prad_gene
for index in  range(0, df_prad_filtered_common.shape[0]):
    diff = df_prad_filtered_common.iloc[index, :].values - df_kirc_filtered_mean.values
    distance = np.dot(diff, np.dot(df_prad_filtered_cov, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))
    
minimum_inter_kirc_prad = np.min(distances)


minimum_inter =  min(minimum_inter_kirc_prad,minimum_inter_prad_kirc)
print("La distancia minima entre PRAD y KIRC es: ", minimum_inter)
overlap_prad_kirc = (max_intra_dist_kirc+max_intra_dist_prad)/(2*minimum_inter)
overlap_prad_kirc

La distancia minima entre PRAD y KIRC es:  432.5592256737801

np.float64(0.23337357871082554)

In [22]:
#PRAD-BRCA
np.random.seed(1)

#df_sampled_brca = df_brca_filtered_common.sample(axis=1, n=14000)
#df_sampled_prad = df_prad_filtered_common.sample(axis=1, n=14000)


#df_brca_filtered_mean = df_brca_filtered_common.mean()
#df_prad_filtered_mean = df_prad_filtered_common.mean()

#df_brca_filtered_cov = df_brca_filtered_common.cov()
#df_prad_filtered_cov = df_prad_filtered_common.cov()

#df_brca_filtered_cov_inv = np.linalg.inv(df_brca_filtered_cov)
#df_prad_filtered_cov_inv = np.linalg.inv(df_prad_filtered_cov)

distances = []
#Take the center of df_prad_mean and brca_gene
for index in  range(0, df_brca_filtered_common.shape[0]):
    diff = df_brca_filtered_common.iloc[index, :].values - df_prad_filtered_mean.values
    distance = np.dot(diff, np.dot(df_brca_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))

minimum_inter_prad_brca = np.min(distances)


distances = []
#Take the center of df_brca_mean and prad_gene
for index in  range(0, df_prad_filtered_common.shape[0]):
    diff = df_prad_filtered_common.iloc[index, :].values - df_brca_filtered_mean.values
    distance = np.dot(diff, np.dot(df_prad_filtered_cov, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))

minimum_inter_brca_prad = np.min(distances)

minimum_inter =  min(minimum_inter_brca_prad,minimum_inter_prad_brca)
print("La distance inter-classe entre PRAD et BRCA est de : ", minimum_inter)
overlap_prad_brca = (max_intra_dist_prad+max_intra_dist_brca)/(2*minimum_inter)
overlap_prad_brca

La distance inter-classe entre PRAD et BRCA est de :  419.0744620931983

np.float64(0.23286057578819708)

### Calculate the overlap for each mahalanobis distance for each cancer type : COAD-BRCA,COAD-LUAD

In [23]:
#COAD-BRCA
np.random.seed(1)

#df_sampled_brca = df_brca_filtered_common.sample(axis=1, n=14000)
#df_sampled_coad = df_coad_filtered_common.sample(axis=1, n=14000)


#df_brca_filtered_mean = df_brca_filtered_common.mean()
#df_coad_filtered_mean = df_coad_filtered_common.mean()

#df_brca_filtered_cov = df_brca_filtered_common.cov()
#df_coad_filtered_cov = df_coad_filtered_common.cov()

#df_brca_filtered_cov_inv = np.linalg.inv(df_brca_filtered_cov)
#df_coad_filtered_cov_inv = np.linalg.inv(df_coad_filtered_cov)

distances = []

#Take the center of df_coad_mean and brca_gene
for index in  range(0, df_brca_filtered_common.shape[0]):
    diff = df_brca_filtered_common.iloc[index, :].values - df_coad_filtered_mean.values
    distance = np.dot(diff, np.dot(df_brca_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))

minimum_inter_coad_brca = np.min(distances)


distances = []

#Take the center of df_brca_mean and coad_gene
for index in range(0, df_coad_filtered_common.shape[0]):
    diff = df_coad_filtered_common.iloc[index, :].values - df_brca_filtered_mean.values
    distance = np.dot(diff, np.dot(df_coad_filtered_cov, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))

minimum_inter_brca_coad = np.min(distances)

minimum_inter =  min(minimum_inter_brca_coad,minimum_inter_coad_brca)
print("La distance inter-classe minimale entre les deux classes COAD et BRCA est de : ", minimum_inter)
overlap_coad_brca = (max_intra_dist_coad+max_intra_dist_brca)/(2*minimum_inter)
overlap_coad_brca

La distance inter-classe minimale entre les deux classes COAD et BRCA est de :  445.3793927067866

np.float64(0.2433921922400454)

In [24]:
#COAD-LUAD
np.random.seed(1)

#df_sampled_luad = df_luad_filtered_common.sample(axis=1, n=14000)
#df_sampled_coad = df_coad_filtered_common.sample(axis=1, n=14000)


#df_luad_filtered_mean = df_luad_filtered_common.mean()
#df_coad_filtered_mean = df_coad_filtered_common.mean()

#df_luad_filtered_cov = df_luad_filtered_common.cov()
#df_coad_filtered_cov = df_coad_filtered_common.cov()

#df_luad_filtered_cov_inv = np.linalg.inv(df_luad_filtered_cov)
#df_coad_filtered_cov_inv = np.linalg.inv(df_coad_filtered_cov)

distances = []

#Take the center of df_coad_mean and luad_gene
for index in  range(0, df_luad_filtered_common.shape[0]):
    diff = df_luad_filtered_common.iloc[index, :].values - df_coad_filtered_mean.values
    distance = np.dot(diff, np.dot(df_luad_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))
    
minimum_inter_coad_luad = np.min(distances)


distances = []

#Take the center of df_luad_mean and coad_gene
for index in range(0, df_coad_filtered_common.shape[0]):
    diff = df_coad_filtered_common.iloc[index, :].values - df_luad_filtered_mean.values
    distance = np.dot(diff, np.dot(df_coad_filtered_cov, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))

minimum_inter_luad_coad = np.min(distances)


minimum_inter =  min(minimum_inter_luad_coad,minimum_inter_coad_luad)
print("La distance inter-classe minimale entre les deux classes LUAD et COAD est de : ", minimum_inter)
overlap_coad_luad = (max_intra_dist_coad+max_intra_dist_luad)/(2*minimum_inter)
overlap_coad_luad

La distance inter-classe minimale entre les deux classes LUAD et COAD est de :  487.1321072350902

np.float64(0.2218515390086327)

Calculate the overlap for each mahalanobis distance for each cancer type : LUAD-BRCA

In [25]:
#LUAD-BRCA
np.random.seed(1)

#df_sampled_luad = df_luad_filtered_common.sample(axis=1, n=14000)
#df_sampled_brca = df_brca_filtered_common.sample(axis=1, n=14000)


#df_luad_filtered_mean = df_luad_filtered_common.mean()
#df_brca_filtered_mean = df_brca_filtered_common.mean()

#df_luad_filtered_cov = df_luad_filtered_common.cov()
#df_brca_filtered_cov = df_brca_filtered_common.cov()

#df_luad_filtered_cov_inv = np.linalg.inv(df_luad_filtered_cov)
#df_brca_filtered_cov_inv = np.linalg.inv(df_brca_filtered_cov)

distances = []

#Take the center of df_brca_mean and luad_gene
for index in  range(0, df_luad_filtered_common.shape[0]):
    diff = df_luad_filtered_common.iloc[index, :].values - df_brca_filtered_mean.values
    distance = np.dot(diff, np.dot(df_luad_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))
    
minimum_inter_brca_luad = np.min(distances)


distances = []

#Take the center of df_luad_mean and brca_gene
for index in range(0, df_brca_filtered_common.shape[0]):
    diff = df_brca_filtered_common.iloc[index, :].values - df_luad_filtered_mean.values
    distance = np.dot(diff, np.dot(df_brca_filtered_cov, diff))
    mahalanobis_distance_abs = np.abs(distance) 
    distances.append(np.sqrt(mahalanobis_distance_abs))

minimum_inter_luad_brca = np.min(distances)


minimum_inter =  min(minimum_inter_luad_brca, minimum_inter_brca_luad)
print("La distance inter-classe minimale entre les deux classes LUAD et BRCA est de : ", minimum_inter)
overlap_brca_luad = (max_intra_dist_brca + max_intra_dist_luad)/(2*minimum_inter)
overlap_brca_luad

La distance inter-classe minimale entre les deux classes LUAD et BRCA est de :  495.8370731763404

np.float64(0.24833028430362172)

In [26]:
#KIRC-COAD
np.random.seed(1)

#df_kirc_filtered_mean = df_kirc_filtered_common.mean()
#df_coad_filtered_mean = df_coad_filtered_common.mean()

#df_kirc_filtered_cov = df_kirc_filtered_common.cov()
#df_coad_filtered_cov = df_coad_filtered_common.cov()

##df_kirc_filtered_cov_inv = np.linalg.inv(df_kirc_filtered_cov)
#df_coad_filtered_cov_inv = np.linalg.inv(df_coad_filtered_cov)

distances = []

# Take the center of df_kirc_mean and coad_gene
for index in range(0, df_coad_filtered_common.shape[0]):
    diff = df_coad_filtered_common.iloc[index, :].values - df_kirc_filtered_mean.values
    distance = np.dot(diff, np.dot(df_coad_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance)
    distances.append(np.sqrt(mahalanobis_distance_abs))

minimum_inter_kirc_coad = np.min(distances)

distances = []

# Take the center of df_coad_mean and kirc_gene
for index in range(0, df_kirc_filtered_common.shape[0]):
    diff = df_kirc_filtered_common.iloc[index, :].values - df_coad_filtered_mean.values
    distance = np.dot(diff, np.dot(df_kirc_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance)
    distances.append(np.sqrt(mahalanobis_distance_abs))

minimum_inter_coad_kirc = np.min(distances)

minimum_inter = min(minimum_inter_kirc_coad, minimum_inter_coad_kirc)
print("La distance inter-classe entre KIRC et COAD est de : ", minimum_inter)
overlap_kirc_coad = (max_intra_dist_kirc + max_intra_dist_coad) / (2 * minimum_inter)
overlap_kirc_coad

La distance inter-classe entre KIRC et COAD est de :  1247335105.8866947

np.float64(8.960209666248247e-08)

In [27]:
#KIRC-LUAD
np.random.seed(1)

#df_kirc_filtered_mean = df_kirc_filtered_common.mean()
#df_luad_filtered_mean = df_luad_filtered_common.mean()

#df_kirc_filtered_cov = df_kirc_filtered_common.cov()
#df_luad_filtered_cov = df_luad_filtered_common.cov()

#df_kirc_filtered_cov_inv = np.linalg.inv(df_kirc_filtered_cov)
#df_luad_filtered_cov_inv = np.linalg.inv(df_luad_filtered_cov)

distances = []

# Take the center of df_kirc_mean and luad_gene
for index in range(0, df_luad_filtered_common.shape[0]):
    diff = df_luad_filtered_common.iloc[index, :].values - df_kirc_filtered_mean.values
    distance = np.dot(diff, np.dot(df_kirc_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance)
    distances.append(np.sqrt(mahalanobis_distance_abs))

minimum_inter_kirc_luad = np.min(distances)

distances = []

# Take the center of df_luad_mean and kirc_gene
for index in range(0, df_kirc_filtered_common.shape[0]):
    diff = df_kirc_filtered_common.iloc[index, :].values - df_luad_filtered_mean.values
    distance = np.dot(diff, np.dot(df_luad_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance)
    distances.append(np.sqrt(mahalanobis_distance_abs))

minimum_inter_luad_kirc = np.min(distances)

minimum_inter = min(minimum_inter_kirc_luad, minimum_inter_luad_kirc)
print("La distance inter-classe minimale entre les deux classes LUAD et KIRC est de : ", minimum_inter)
overlap_kirc_luad = (max_intra_dist_kirc + max_intra_dist_luad) / (2 * minimum_inter)
overlap_kirc_luad

La distance inter-classe minimale entre les deux classes LUAD et KIRC est de :  85585794.7435013

np.float64(1.4779711479922166e-06)

In [28]:
#BRCA-KIRC
np.random.seed(1)

#df_brca_filtered_mean = df_brca_filtered_common.mean()
#df_kirc_filtered_mean = df_kirc_filtered_common.mean()

#df_brca_filtered_cov = df_brca_filtered_common.cov()
#df_kirc_filtered_cov = df_kirc_filtered_common.cov()

#df_brca_filtered_cov_inv = np.linalg.inv(df_brca_filtered_cov)
#df_kirc_filtered_cov_inv = np.linalg.inv(df_kirc_filtered_cov)

distances = []

# Take the center of df_kirc_mean and brca_gene
for index in range(0, df_brca_filtered_common.shape[0]):
    diff = df_brca_filtered_common.iloc[index, :].values - df_kirc_filtered_mean.values
    distance = np.dot(diff, np.dot(df_brca_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance)
    distances.append(np.sqrt(mahalanobis_distance_abs))

minimum_inter_kirc_brca = np.min(distances)

distances = []

# Take the center of df_brca_mean and kirc_gene
for index in range(0, df_kirc_filtered_common.shape[0]):
    diff = df_kirc_filtered_common.iloc[index, :].values - df_brca_filtered_mean.values
    distance = np.dot(diff, np.dot(df_kirc_filtered_cov_inv, diff))
    mahalanobis_distance_abs = np.abs(distance)
    distances.append(np.sqrt(mahalanobis_distance_abs))

minimum_inter_brca_kirc = np.min(distances)

minimum_inter = min(minimum_inter_kirc_brca, minimum_inter_brca_kirc)
print("La distance inter-classe entre BRCA et KIRC est de : ", minimum_inter)
overlap_brca_kirc = (max_intra_dist_brca + max_intra_dist_kirc) / (2 * minimum_inter)
overlap_brca_kirc

La distance inter-classe entre BRCA et KIRC est de :  321450325.4952584

np.float64(3.9453745829095897e-07)

In [29]:
df_prad.head()

,gene_1,gene_2,gene_3,gene_4,gene_6,gene_11,gene_12,gene_19,gene_20,gene_22,...,gene_20520,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529
0,2.017209,3.265527,5.478487,10.431999,7.175175,1.334282,2.015391,5.619994,1.334282,9.796088,...,7.205236,4.926711,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759
2,3.511759,4.327199,6.881787,9.870730,6.972130,0.452595,1.981122,8.210248,4.195285,8.970920,...,10.336027,5.125213,8.127123,10.908640,5.401607,9.911597,9.045255,9.788359,10.090470,1.683023
3,3.663618,4.507649,6.659068,10.196184,7.843375,0.434882,2.874246,8.306317,3.573556,8.524616,...,9.194823,6.076566,8.792959,10.141520,8.942805,9.601208,11.392682,9.694814,9.684365,3.292001
5,3.467853,3.581918,6.620243,9.706829,7.758510,0.515410,2.516797,6.842765,2.809661,7.663935,...,7.831035,5.726657,8.602588,9.928339,6.096154,9.816001,11.556995,9.244150,9.836473,5.355133
7,2.854853,1.750478,7.226720,9.758691,5.952103,0.000000,2.405856,7.373431,2.304861,8.922008,...,6.460507,5.297833,8.277092,9.599230,5.244290,9.994339,12.670377,9.987733,9.216872,6.551490

In [30]:
# add the class column to the dataframes
df_prad_filtered_common['Class'] = 'PRAD'
df_luad_filtered_common['Class'] = 'LUAD'
df_brca_filtered_common['Class'] = 'BRCA'
df_kirc_filtered_common['Class'] = 'KIRC'
df_coad_filtered_common['Class'] = 'COAD'

In [31]:
# merge the common dataframes to get the final dataframe and save it to a csv file
df_final = pd.concat([df_prad_filtered_common, df_luad_filtered_common, df_brca_filtered_common, df_kirc_filtered_common, df_coad_filtered_common], axis=0)

# Make sure to add the Class column to the final DataFrame USING FILTERED DATA
#df_final['Class'] = pd.concat([filtered_data[filtered_data['Class'] == 'PRAD']['Class'], 
#                               filtered_data[filtered_data['Class'] == 'LUAD']['Class'], 
#                               filtered_data[filtered_data['Class'] == 'BRCA']['Class'], 
#                               filtered_data[filtered_data['Class'] == 'KIRC']['Class'], 
#                               filtered_data[filtered_data['Class'] == 'COAD']['Class']], axis=0)
df_final.to_csv('data\\final_df.csv', index=False)

In [32]:
# read final csv file
df_final = pd.read_csv('data\\final_df.csv')
df_final.shape

(801, 4001)

In [33]:
df_final['Class'].value_counts()

Class
BRCA    300
KIRC    146
LUAD    141
PRAD    136
COAD     78
Name: count, dtype: int64

In [34]:
# Print the inter-class values of each pair
print(f"Inter-class PRAD-LUAD: {minimum_inter_prad_luad}")

Inter-class PRAD-LUAD: 680588901.6935996